"""Enforce relations and remove unique names

Revision ID: 583b4e179d79
Revises: dd25179fe322
Create Date: 2026-04-29 11:02:53.613300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583b4e179d79'
down_revision = 'dd25179fe322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    with op.batch_alter_table('cari', schema=None) as batch_op:
        batch_op.alter_column('aktif_mi',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('fabrika', schema=None) as batch_op:
        batch_op.alter_column('aktif_mi',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    with op.batch_alter_table('fis', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_fis_cari_kodu_cari'), 'cari', ['cari_kodu'], ['firma_kodu'])
        batch_op.create_foreign_key(batch_op.f('fk_fis_fabrika_kodu_fabrika'), 'fabrika', ['fabrika_kodu'], ['firma_kodu'])

    with op.batch_alter_table('stok_bildirim', schema=None) as batch_op:
        batch_op.alter_column('birim',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.create_foreign_key(batch_op.f('fk_stok_bildirim_gelecek_stok_id_gelecek_stok'), 'gelecek_stok', ['gelecek_stok_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stok_bildirim_fis_id_fis'), 'fis', ['fis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stok_bildirim', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stok_bildirim_fis_id_fis'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stok_bildirim_gelecek_stok_id_gelecek_stok'), type_='foreignkey')
        batch_op.alter_column('birim',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('fis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fis_fabrika_kodu_fabrika'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_fis_cari_kodu_cari'), type_='foreignkey')

    with op.batch_alter_table('fabrika', schema=None) as batch_op:
        batch_op.alter_column('aktif_mi',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('cari', schema=None) as batch_op:
        batch_op.alter_column('aktif_mi',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('_alembic_tmp_cari',
    sa.Column('firma_kodu', sa.VARCHAR(length=20), nullable=False),
    sa.Column('firma_adi', sa.VARCHAR(length=200), nullable=False),
    sa.Column('vergi_dairesi', sa.VARCHAR(length=100), nullable=True),
    sa.Column('vergi_numarasi', sa.VARCHAR(length=50), nullable=True),
    sa.Column('firma_adres', sa.TEXT(), nullable=True),
    sa.Column('e_posta', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefon_no', sa.VARCHAR(length=20), nullable=True),
    sa.Column('aktif_mi', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('firma_kodu'),
    sa.UniqueConstraint('firma_adi')
    )
    # ### end Alembic commands ###
