"""Initial migration

Revision ID: dd25179fe322
Revises: 
Create Date: 2026-04-29 09:30:28.586726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd25179fe322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cari', schema=None) as batch_op:
        batch_op.alter_column('aktif_mi',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('fabrika', schema=None) as batch_op:
        batch_op.alter_column('aktif_mi',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('fis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cari', ['cari_kodu'], ['firma_kodu'])
        batch_op.create_foreign_key(None, 'fabrika', ['fabrika_kodu'], ['firma_kodu'])

    with op.batch_alter_table('stok_bildirim', schema=None) as batch_op:
        batch_op.alter_column('birim',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stok_bildirim', schema=None) as batch_op:
        batch_op.alter_column('birim',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('fis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fabrika', schema=None) as batch_op:
        batch_op.alter_column('aktif_mi',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('cari', schema=None) as batch_op:
        batch_op.alter_column('aktif_mi',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
